### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by BenParizek** [DavidBelicza/PHP-Science-TextRank#11]
I have a package that uses TextRank that will need to support PHP 8 soon. Would that be easy enough to add to the current release or is that something that will be better added to v2.0.0?

```
"require": {
  "php": "7.* || ^8.0",
}
```

**Comment by DavidBelicza** [comment]
@BenParizek The current release 1.1.1 would work on PHP 8 if restrictions are removed from composer.json. However, I'm releasing a new version that sets the minimum to 7.4 and also updates the php-unit to 9.

**Comment by BenParizek** [comment]
Thanks!
