### ISSUE TITLE
Why it can only detect one word?

### ISSUE THREAD

**Issue by erikdemarco** [DavidBelicza/PHP-Science-TextRank#14]
Other old project based on TextRank (https://github.com/crodas/TextRank)
can extract most popular keywords from text including two or three keywords.

For example this text:
lorem ipsum only lorem ipsum sample

It will only extract:
lorem
ipsum

Instead of:
lorem ipsum

**Comment by DavidBelicza** [comment]
This implementation of the algorithm extracts the tokens (words) rather than phrases.
