### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by vincentsch** [DavidBelicza/PHP-Science-TextRank#4]
src/Tool/Score.php:
`protected function normalize(int $value, int $min, int $max): float
    {
        $normalized = ($value - $min) / ($max - $min);
        return $normalized;
    }`

When $max and $min have the same value there's a division by zero.

**Comment by khalwat** [comment]
I'm running into this as well when attempting to do something simple like:

```
$api->getOnlyKeyWords("Nothing to look at here");
```

**Comment by khalwat** [comment]
Looks to be fixed via: https://github.com/nexxome/PHP-Science-TextRank/commit/79558be89a381102346fbcdacbb534dd1cd2bbea

**Comment by DavidBelicza** [comment]
@vincentsch @khalwat thank for the report. I'll fix it soon.

**Comment by DavidBelicza** [comment]
Fixed in the last release: 1.0.4, https://github.com/DavidBelicza/PHP-Science-TextRank/releases/tag/1.0.4
