### ISSUE TITLE
How to Install with out Composer

### ISSUE THREAD

**Issue by kezenwa** [DavidBelicza/PHP-Science-TextRank#9]
Don't use Composer and have no interest in ever using Composer as I love to keep things simple while reducing unnecessary Point of Errors / Bugs / Maintenance.

Kindly let me know if I can use this your script without Composer and probably how to go about it if it isn't as simple as Requiring the file **TextRankFacade.php**

Thanks

**Comment by mvcaaa** [comment]
You need all the files from `src` folder and you need to specify where and how to look for specific classes/namespaces(autoloading). 

This is weird. Composer is de facto standard - why not use it ? 
Composer will take care for all the stuff for you, including autoloading, dependency management (when your project become bigger there will be more libs right ?) and updates - all for free.

Consider learning how to use it, this is a good tool everyone use every day.
